### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by dphroon** [andrewleech/ha_magiqtouch#1]
Hi,
This looks fantastic and very promising.... have you been running this on your own system?  I'd love to try it out too

Willing to help if you need anything, testing etc

**Comment by andrewleech** [comment]
It's not really ready yet unfortunately, I haven't had time to finish it off yet. It connects, reads currently settings, but changing settings doesn't really work. It also seems to lose the connection after a while.

**Comment by palitu** [comment]
@andrewleech  - super keen for this!  have you seen this project? https://github.com/mrhteriyaki/airconcontrol

It is a win forms replacement for the magiqtouch app.  Potentially you could get some hints as to what is happening from that one.

Would be happy for just reading the settings/state in HA if you are happy to make it available in HACs?

cheers.

**Comment by andrewleech** [comment]
It is already available in HACS in general, but it sounds like there are still module dependency issues breaking install for some people.

As far as the rest of the mqtt communication to get/set the state I did previously have the format of that worked out and working (though suspect I might have lost a bit when my server died last year).

When I had it mostly working last time though there were some issues in the conversion of mqtt state to HA controls, and stability issues (it died after a few hours, probably a mqtt login/refresh issue).

The problem for me is far too many active projects, very little spare time, so yeah not a lot of progress.

**Comment by palitu** [comment]
haha, yeah... always lots going on!

I will be getting my A/C installed next friday, so i will be giving it a go!  If i can figure any of the issue out, i will let you know / PR.  

BTW, are you using gitlab or github?

**Comment by dphroon** [comment]
Yes, I haven't been able to install the integration - keeps stopping with a config flow error.

**Comment by dpdump** [comment]
> Yes, I haven't been able to install the integration - keeps stopping with a config flow error.

I’m getting the same error.

**Comment by dphroon** [comment]
something to do with the mandate.git package in the requirements section in manifest.json.
Replacing it with the published mandate package allows it to progress past the config flow error, but it still doesn't allow login

**Comment by raym777** [comment]
Just wondering if there's been any progress on this? I'm also unable to get beyond the config flow error. Any update appreciated.

**Comment by andrewleech** [comment]
Sorry no I've got far too many projects on the go, this one hasn't made it back to the top of the list yet!

**Comment by Prosatanos** [comment]
Hey
Also getting the config flow error. We really appreciate  that you have gotten it this far.

Thanks!

**Comment by Prosatanos** [comment]
> something to do with the mandate.git package in the requirements section in manifest.json. Replacing it with the published mandate package allows it to progress past the config flow error, but it still doesn't allow login

How did you manage to do this? Any tips?

**Comment by DeltaTangoLima** [comment]
> How did you manage to do this? Any tips?

I did it by exec'ing an interactive bash shell in my Home Assistant docker container and using pip to install the mandate module manually.  Still can't login to the Seeley service though.

**Comment by epetousis** [comment]
If anyone's looking for a "just works" solution, [I've hacked in](https://github.com/epetousis/ha_magiqtouch) the newer web based API using [research from mrhteriyaki](https://github.com/mrhteriyaki/MagIQTouch-Control). Still experimental and doesn't support anything more than simple on/off and temperature control, but at least you can sign in now.

**Comment by dphroon** [comment]
> If anyone's looking for a "just works" solution, [I've hacked in](https://github.com/epetousis/ha_magiqtouch) the newer web based API using [research from mrhteriyaki](https://github.com/mrhteriyaki/MagIQTouch-Control). Still experimental and doesn't support anything more than simple on/off and temperature control, but at least you can sign in now.

@epetousis Looks good - it fails at login for me though;
2022-08-19 22:29:02.498 ERROR (MainThread) [custom_components.MagiQtouch.config_flow] Could not connect: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token" Traceback (most recent call last):

**Comment by epetousis** [comment]
> @epetousis Looks good - it fails at login for me though; 2022-08-19 22:29:02.498 ERROR (MainThread) [custom_components.MagiQtouch.config_flow] Could not connect: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token" Traceback (most recent call last):

Looks like the workaround I implemented in code didn't work, I'll look into a better fix later. In the meantime, try exporting `AWS_EC2_METADATA_DISABLED=true` as an environment variable in Home Assistant's shell environment. In my Docker configuration for Home Assistant, I've done it like so:

```
---
version: '2'
services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    privileged: true
    environment:
      - AWS_EC2_METADATA_DISABLED=true
```

**Comment by DeltaTangoLima** [comment]
> Looks like the workaround I implemented in code didn't work, I'll look into a better fix later. In the meantime, try exporting `AWS_EC2_METADATA_DISABLED=true` as an environment variable in Home Assistant's shell environment. In my Docker configuration for Home Assistant, I've done it like so:

This worked perfectly for me! Thank you. Now I can get rid of my unstable Home Assistant | node-red | Alexa automations!

**Comment by dphroon** [comment]
> > @epetousis Looks good - it fails at login for me though; 2022-08-19 22:29:02.498 ERROR (MainThread) [custom_components.MagiQtouch.config_flow] Could not connect: Connect timeout on endpoint URL: "http://169.254.169.254/latest/api/token" Traceback (most recent call last):
> 
> Looks like the workaround I implemented in code didn't work, I'll look into a better fix later. In the meantime, try exporting `AWS_EC2_METADATA_DISABLED=true` as an environment variable in Home Assistant's shell environment. In my Docker configuration for Home Assistant, I've done it like so:
> 
> ```
> ---
> version: '2'
> services:
>   homeassistant:
>     image: ghcr.io/home-assistant/home-assistant:stable
>     restart: unless-stopped
>     privileged: true
>     environment:
>       - AWS_EC2_METADATA_DISABLED=true
> ```

I'm using Home Assistant OS - not sure I can easily export variables. Unless someone knows?

**Comment by epetousis** [comment]
I've fixed the other broken AWS Cognito connection in the login flow. You should be able to pull my latest changes and log in without any environment variables needed.

**Comment by dphroon** [comment]
> I've fixed the other broken AWS Cognito connection in the login flow. You should be able to pull my latest changes and log in without any environment variables needed.

Nice! works perfectly now thanks!

**Comment by raym777** [comment]
> 

Really appreciate the effort in getting this working. Having some trouble though... I re-installed the integration via HACS and when I try to set in up in HA, I get the error: "This integration does not support configuration via the UI". 

I gather I've done something wrong or need to set this up manually. Any help is appreciated...

**Comment by KaiboshOz** [comment]
> "This integration does not support configuration via the UI".

I had the same thing happen.  Complete removal of the integration and reboot of the host (not just the HA instance) followed by reinstalling fixed it for me..

**Comment by DeltaTangoLima** [comment]
> I had the same thing happen. Complete removal of the integration and reboot of the host (not just the HA instance) followed by reinstalling fixed it for me..

Yeah - happened to me a couple of times. I find it also gets out of sync with the cloud service at times - doesn't track the on/off state, or temperature changes made at the panel (or with the app).

But, as an alpha release, I'm really, really happy with it. This is (will be) the final piece of my climate management puzzle.

**Comment by raym777** [comment]
> > "This integration does not support configuration via the UI".
> 
> I had the same thing happen. Complete removal of the integration and reboot of the host (not just the HA instance) followed by reinstalling fixed it for me..

Thanks! That worked.



> >
> Yeah - happened to me a couple of times. I find it also gets out of sync with the cloud service at times - doesn't track the on/off state, or temperature changes made at the panel (or with the app).
> 
> But, as an alpha release, I'm really, really happy with it. This is (will be) the final piece of my climate management puzzle.

I'm also noticing this - doesn't sync with changes made at the wall panel but also isn't reflecting changes in current room temp for me either - or any setpoint changes. At least I can automate the on/off state of the device at least so for this, I'm very grateful. Thanks!

**Comment by raym777** [comment]
To clarify my last comment regarding setpoint, my system is central heating only, no cooling. I presume setpoint changes should only apply to when the thermostat is in "override" mode - and not auto/program mode? I guess this might be why setpoint has no effect for me because I don't see any override/manual mode available to me. The only hvac attributes I have are: off, cool, fan_only and auto.

**Comment by dphroon** [comment]
It's a great leap forward!
There's two things I think need work next
- it stops syncing after a while (not sure after what time period). Reloading the integration reconnects it. Probably needs to log into the system again after a while.
- Only has auto / cool / fan /off. Is auto = heat? or does it need a heat option as well. Or can it tell what systems are installed?

**Comment by dphroon** [comment]
> It's a great leap forward! There's two things I think need work next
> 
> * it stops syncing after a while (not sure after what time period). Reloading the integration reconnects it. Probably needs to log into the system again after a while.
> * Only has auto / cool / fan /off. Is auto = heat? or does it need a heat option as well. Or can it tell what systems are installed?

Actually - I think this integration is causing a more general failure in my Home Assistant setup. Most sensors are no longer available at the same time Magiqtouch stops communicating. Something is stuck in a loop somewhere? Disabling this integration tonight to see if it resolves, and then will investigate further.

**Comment by epetousis** [comment]
@dphroon I've noticed the updating issue as well - not 100% on what's causing it, but it's possible that I broke something by moving to that new API. I'll have to take a look when I get some free time next, I'll probably push it alongside/after the multi-zone support that I'm working on.

As for the auto/cool/fan/off thing, I believe auto corresponds to heat right now, but I'm also working on improving this so that the modes are correctly set based off of what's hooked up to the control panel.

**Comment by raym777** [comment]
> @dphroon I've noticed the updating issue as well - not 100% on what's causing it, but it's possible that I broke something by moving to that new API. I'll have to take a look when I get some free time next, I'll probably push it alongside/after the multi-zone support that I'm working on.
> 
> As for the auto/cool/fan/off thing, I believe auto corresponds to heat right now, but I'm also working on improving this so that the modes are correctly set based off of what's hooked up to the control panel.

Thanks for that. As others have mentioned also, I'm noticing that it frequently loses its connection and no longer controls anything. I need to reload the integration to restore functionality (and re-sync).

**Comment by raym777** [comment]
Also, for me, with a heating system only, auto corresponds to "program" mode. For manual control, I use "override" on the wall panel or app but this is not yet available via the integration. So I think there should be separate heat and cool modes (allowing setpoint control via the integration - ie, override mode) AND auto for program mode where dialling in a setpoint manually probably doesn't make sense. Thanks again for getting it all working this far!

**Comment by epetousis** [comment]
I've fixed the failing state refresh, was a mistake on my part - the entity wasn't calling the async refresh method in the driver properly. It's pretty inefficient and each zone calls the refresh method, so multiple refreshes happen at once, I'll fix this soon. I've also added rudimentary support for multiple zones. Auto mode support has not been added yet - haven't yet looked into it.

**Comment by DeltaTangoLima** [comment]
> I've fixed the failing state refresh, was a mistake on my part

@epetousis I've tried your updated commit, even removed and reinstalled completely, and am getting the below error in my Home Assistant logs. The integration logs in successfully, but creates no entities.

```
2022-08-24 18:33:06.972 WARNING (MainThread) [magiqtouch] The MagiQtouch API is reporting no zones. No devices will be available from the MagiQtouch integration.
```

I've checked my MagiQtouch app and profile settings, and can't see anything related to zones.

**Comment by epetousis** [comment]
@DeltaTangoLima whoops, I don't know why I assumed that zoneless systems weren't a thing. Pushed a hotfix, let me know if that works for you.

**Comment by DeltaTangoLima** [comment]
@epetousis Cheers! It's loading correctly now - now to see if it stays in sync. I'll let you know.

**Comment by DeltaTangoLima** [comment]
@epetousis Hmmmm - still appears to be losing sync. Showing as off, with 0°/0° for the setpoint/current temp.

**Comment by epetousis** [comment]
@DeltaTangoLima do you happen to see any logs from the integration?

**Comment by DeltaTangoLima** [comment]
@epetousis no, nothing since I restarted Home Assistant after your hotfix. The last log entries contain what look like a json payload of some sort, with the final one being about 5 or 6 minutes after the restart, then nothing.

The log entries all look pretty much identical (line breaks added - this is all a single line in the logfile):

```
WARNING (SyncWorker_6) [magiqtouch] Sent: {"SerialNo": "[REDACTED]",
"TimeRequest": "2022-08-24T18:59:43.178332+10:00","StandBy": 0,"EvapCRunning": 0,
"CTemp": 23,"CFanSpeed": 0,"CFanOnly": 0,"CThermosOrFan": 0,"HRunning": 1,"HTemp": 23,
"HFanSpeed": 10,"HFanOnly": 0,"FAOCRunning": 0,"FAOCTemp": 23,"IAOCRunning": 0,
"IAOCTemp": 23,"OnOffZone1": 1,"TempZone1": 23,"Override1": 1,"OnOffZone2": 0,
"TempZone2": 0,"Override2": 0,"OnOffZone3": 0,"TempZone3": 0,"Override3": 0,"OnOffZone4": 0,
"TempZone4": 0,"Override4": 0,"OnOffZone5": 0,"TempZone5": 0,"Override5": 0,"OnOffZone6": 0,
"TempZone6": 0,"Override6": 0,"OnOffZone7": 0,"TempZone7": 0,"Override7": 0,"OnOffZone8": 0,
"TempZone8": 0,"Override8": 0,"OnOffZone9": 0,"TempZone9": 0,"Override9": 0,"OnOffZone10": 0,
"TempZone10": 0,"Override10": 0,"CC3200FW_Major": 0,"CC3200FW_Minor": 0,"STM32FW_Major": 0,
"STM32FW_Minor": 0,"TouchCount": 0,"CCL": null,"STL": null}
```

**Comment by epetousis** [comment]
Interesting, I just got the same issue on my Home Assistant install. I'll enable debug logs and see if I can spot anything.

**Comment by epetousis** [comment]
Looks like the issue was the refresh method wasn't properly throwing an exception when the authentication token expired, so the Home Assistant state was being set to blank defaults, and a reauthentication request wasn't being triggered. I believe my latest fix should work, but I haven't tested long-term yet.

**Comment by DeltaTangoLima** [comment]
No worries - have loaded it up, but about to head away for a few days, so won't be able to check the long-term fix myself either. Will let you know when I get back.

**Comment by KaiboshOz** [comment]
@epetousis - Still looking good, maintaining sync after about 5 hours here..

**Comment by epetousis** [comment]
Yeah, looking good for me as well now.

**Comment by KaiboshOz** [comment]
Poop.. 
After restart following HA 2022.8.7 update:
```
Logger: homeassistant.setup
Source: setup.py:192
First occurred: 10:02:59 AM (1 occurrences)
Last logged: 10:02:59 AM

Setup failed for custom integration MagiQtouch: Unable to import component: cannot import name 'resolve_checksum_context' from 'botocore.client' (/usr/local/lib/python3.10/site-packages/botocore/client.py)
```

Working without error notification following another restart..

**Comment by epetousis** [comment]
Yeah, that botocore error's a weird error that I'm yet to figure out. It comes and goes for me as well, but as you observed generally a restart makes it go away.

**Comment by raym777** [comment]
Updated to the latest build 2 days ago and sync looks really good now. HVAC modes look spot on now too!

Only "issue" I've encountered is that the setpoint seems to default to the max_temp whenever the system is shut off. The temp is programmed in my case to 22 degrees but always defaults to 27 when off.  It doesn't automatically update when the system is back on either. 

Other observations:

Adjusting the setpoint in HA appears to have no effect if the system is in a pre-programmed schedule. This probably makes sense. If the system is in "override" mode however, then the temp can be adjusted through this integration but as there's currently no distinction b/w these 2 modes of operation in HA, it may cause confusion for some. 

If I encounter anything else over the next few days I'll post back here. 

Really appreciate getting this so functional now!

**Comment by epetousis** [comment]
> Only "issue" I've encountered is that the setpoint seems to default to the max_temp whenever the system is shut off. The temp is programmed in my case to 22 degrees but always defaults to 27 when off. It doesn't automatically update when the system is back on either.

Interesting one, do you find that when this happens, the temperature on the thermostat is also 27, or is it out of sync entirely?

> Adjusting the setpoint in HA appears to have no effect if the system is in a pre-programmed schedule. This probably makes sense. If the system is in "override" mode however, then the temp can be adjusted through this integration but as there's currently no distinction b/w these 2 modes of operation in HA, it may cause confusion for some.

Yet to take a look into program mode - it looks like this should be possible to do from the integration based off of what the API is returning, but haven't written anything in particular to integrate with it.

**Comment by raym777** [comment]
Yeah, it's entirely out of sync with the thermostat, which shows a setpoint of 22. But again, when in program mode, the setpoint changes in HA appear to have no effect - which I think is correct. Since I'm in this mode 99% of the time, might have something to do with that. 

Perhaps if you do get a chance to take a look at this, I would suggest that any setpoint change whilst in a program mode should flick the system into the in-built override mode. Changes to setpoint appear to work OK when in override.

**Comment by DeltaTangoLima** [comment]
~~For what it's worth, my setpoint syncs perfectly across all three (touch panel, Seeley app, and HA), no matter where I adjust it.~~

Edit: sorry - scratch that. Just realised the talk about setpoint syncing was when it was operating in pre-programmed mode. I only use HA or touch panel to manage climate, so haven't come across this issue.

**Comment by KaiboshOz** [comment]
Ref to @epetousis fork

Another error immediately after upgrade similar to the one mentioned earlier in this thread (https://github.com/andrewleech/ha_magiqtouch/issues/1#issuecomment-1227875027)
Admittedly I didn't bother to check the error message and am just assuming that the error was similar since the circumstances are identical - notification that it was with MagiQtouch integration and it hadn't loaded.. But as before, a reboot fixed things..

Not a big deal since it's pretty obvious right after an upgrade and easy to just reboot again..  Just posting here as an FYI since it's happened twice, both during HA core update (on HASSOS)..

**Comment by dphroon** [comment]
> Ref to @epetousis fork
> 
> Another error immediately after upgrade similar to the one mentioned earlier in this thread ([#1 (comment)](https://github.com/andrewleech/ha_magiqtouch/issues/1#issuecomment-1227875027)) Admittedly I didn't bother to check the error message and am just assuming that the error was similar since the circumstances are identical - notification that it was with MagiQtouch integration and it hadn't loaded.. But as before, a reboot fixed things..
> 
> Not a big deal since it's pretty obvious right after an upgrade and easy to just reboot again.. Just posting here as an FYI since it's happened twice, both during HA core update (on HASSOS)..

Same here. Reboot fixed it.

Not sure if it's related or not though.

Google home app was reporting the device was offline just prior to doing the upgrade.

**Comment by mrhteriyaki** [comment]
I can recall having some info sync issues back when the mobile update earlier this year occured.
I'm pretty sure it was the changes to AWS_CLIENT_ID and AWS_POOL_ID values that got it working for me.
[(see here)](https://github.com/mrhteriyaki/MagIQTouch-Control/blob/master/AWSMQTT/AWS_MQTT.cs) if you want to try the newer values.

The older app sent an mqtt request at startup to trigger some sort of status update from the unit. 
I found leaving the app open for long enough it would also show an out of sync temperature value from the wall panel.

**Comment by epetousis** [comment]
That's interesting. The changes in #5 mean the integration is primarily using the HTTP endpoint to sync data, as I thought the MQTT requests were a legacy way of interacting with the API, but it sounds like it's more complex than that.

Does that MQTT status update push data from the unit or is it some kind of health check? If it's the former, it could be useful for fixing the delay between changing settings and seeing those changes reflected.

**Comment by andrewleech** [comment]
For everyone watching this, #5 has been merged now (with a few extra commits on top) so you should be able to install with HACS and try it out! Thanks @epetousis !

**Comment by mrhteriyaki** [comment]
If I recall correctly all MQTT functions were removed from the mobile app but the unit still seems to use it.
I believe they replaced the same status update request with this web call but not sure if it improves the delay.
See RefreshData function here: 
[https://github.com/mrhteriyaki/MagIQTouch-Control/blob/master/SeeleyControl/SCData.cs](https://github.com/mrhteriyaki/MagIQTouch-Control/blob/master/SeeleyControl/SCData.cs)

I'm also not sure if the AWS IDs were a part of it too, I got the feeling there were 2 backend systems and they were migrating systems, mine stopped working weeks after the app was updated. I'm not familiar with AWS to know the significance of the IDs only that they've been changed in the app.

**Comment by andrewleech** [comment]
FYI I got sick of trying to make the mode vs fan controls work well with the standard Thermostat card, so I've made my own custom card!
![image](https://user-images.githubusercontent.com/3318786/208207884-6776e89f-8182-451a-acae-52973f508039.png)
For details check out https://github.com/andrewleech/lovelace-magiqtouch-thermostat

**Comment by DeltaTangoLima** [comment]
@andrewleech I'd be really interested in understanding what issues you've been having. I've tried the stock climate card, my (preferred) [mini climate card](https://github.com/artem-sedykh/mini-climate-card), ~~and now your new one,~~ and I have the same problem with all of them.

Edit: I take that back - tried your card again this morning, and now it works! No idea WTH was going on with that. Leaving the rest of my comment here for discussion, if required.

¯\\\_(ツ)_/¯

My setup is that MagiQtouch controller is plugged into my evap, which is daisy-chained to the heater unit (all brand new in the past few years, this is how Braemar recommended it).

The problems I have are:

- if I try to turn on cooling _AND_ cooling was the last mode it was operating in, it starts cooling
- if I switch to heating _OR_ heating was the last mode it was operating in, it will stick to heating
- I can always switch between heating and fan mode without issues but, again, it's the last fan mode that was used (either cooling fan - fresh air - or heating fan)

I'm just wondering if the JSON your integration sends is documented anywhere, or if it's something you figured out for yourself.

I'm seeing this one warning (see sample below, line breaks added for legibility) in the HA logs that seems to indicate that, at least seems to indicate in this instance that it attempted to start both cooling (`EvapCRunning: 1`) and heating (`HRunning: 1`) simultneously.

And, all subsequent warning entries in the logs, regardless of which mode I attempted to move, had `EvapCRunning: 0` and `HRunning: 1` set. Where I attempted to move to fan mode, it had `HFanOnly: 1` set, as well as a positive value for `HFanSpeed`.

Side note: it would be great to figure out how to move to `CFanOnly: 1` instead, as it would mean blowing fresh air through the house too. Maybe for a later update...

```
2022-12-18 10:09:41.633 WARNING (SyncWorker_58) [magiqtouch] Sent: {"SerialNo": "[redacted]]",
"TimeRequest": "2022-12-18T10:09:41.282731+11:00","StandBy": 0,"EvapCRunning": 1,"CTemp": 22,
"CFanSpeed": 0,"CFanOnly": 0,"CThermosOrFan": 1,"HRunning": 1,"HTemp": 22,"HFanSpeed": 0,
"HFanOnly": 0,"FAOCRunning": 0,"FAOCTemp": 22,"IAOCRunning": 0,"IAOCTemp": 22,"OnOffZone1": 1,
"TempZone1": 22,"Override1": 0,"OnOffZone2": 0,"TempZone2": 0,"Override2": 0,"OnOffZone3": 0,
"TempZone3": 0,"Override3": 0,"OnOffZone4": 0,"TempZone4": 0,"Override4": 0,"OnOffZone5": 0,
"TempZone5": 0,"Override5": 0,"OnOffZone6": 0,"TempZone6": 0,"Override6": 0,"OnOffZone7": 0,
"TempZone7": 0,"Override7": 0,"OnOffZone8": 0,"TempZone8": 0,"Override8": 0,"OnOffZone9": 0,
"TempZone9": 0,"Override9": 0,"OnOffZone10": 0,"TempZone10": 0,"Override10": 0,"CC3200FW_Major": 0,
"CC3200FW_Minor": 0,"STM32FW_Major": 0,"STM32FW_Minor": 0,"TouchCount": 0,"CCL": null,"STL": null}
```

**Comment by andrewleech** [comment]
Hi @DeltaTangoLima unfortunately the json is not documented anywhere. I figured it out initially by running the phone app via a sniffing proxy to see what it sends for each setting. Since then it's been more inspecting the return json format to infer what might go into the settings json.

I don't have a heater on magiqtouch, only evap, so I'm not surprised at some glitches with heating settings.
 I wasn't sure if heating also supported fan speed setting mode as opposed to "heat to temperature" mode.

The ability to clearly show / control the "fan speed" vs "temperature" modes of cooling was the main reason I made my own card, I couldn't come up with an intuitive way to do this with the built in card. 

Switching from off or "fan only" to cooling mode such that it uses the same settings cooling used previously was particularly difficult with standard HA climate controls.

I think the controls on my card should work for heating, but the json being sent for switching from temperature to fan possibly need tweaking for heating mode.

Oh, and how you say fan things weren't working for any of the cards, then started working better? Hopefully that was from the magiqtouch integration updating, I did fix a few things here.

**Comment by andrewleech** [comment]
> Side note: it would be great to figure out how to move to CFanOnly: 1 instead, as it would mean blowing fresh air through the house too.

Isn't this just fan-only mode, no heat or cool?

This is the fan mode button in between off and cool modes - it's my most used mode!

Is there something wrong with that button on your system?

**Comment by DeltaTangoLima** [comment]
> Oh, and how you say fan things weren't working for any of the cards, then started working better? Hopefully that was from the magiqtouch integration updating, I did fix a few things here.

That's probably it - I'd only just migrated back to your repo from a fork I tried out a few months back. Probably didn't come good until a restart of HA.

> I think the controls on my card should work for heating, but the json being sent for switching from temperature to fan possibly need tweaking for heating mode.

I'm happy to have play a via the CLI, and try a bunch of different things, if you think that'll help at all. I see you recently committed a change to `magiqtouch.py` to allow for CLI testing - any special tricks I should be aware of?

> Isn't this just fan-only mode, no heat or cool?

Kinda, but kinda not. With the dual appliance setup I have, fan-only mode lets me select the fan for the heater unit (so recycled air) or the fan for the evaporative unit (so fresh air).

Switching to fan-only mode with your HA integration seems to select the fan mode based on the last heat/cool mode that was used. I think it's a problem in their Android app too - I can only select which fan on the wall panel, but not in their app.

**Comment by andrewleech** [comment]
> I'm happy to have play a via the CLI, and try a bunch of different things, if you think that'll help at all. I see you recently committed a change to `magiqtouch.py` to allow for CLI testing - any special tricks I should be aware of?

The CLI can be used to query the current state json in demand, I use it like `poetry run python custom_components/magiqtouch/magiqtouch.py -e <email> -p '<password>'`
It doesn't currently have any way to change settings though.

> 
> > Isn't this just fan-only mode, no heat or cool?
> 
> Kinda, but kinda not. With the dual appliance setup I have, fan-only mode lets me select the fan for the heater unit (so recycled air) or the fan for the evaporative unit (so fresh air).
> 
> Switching to fan-only mode with your HA integration seems to select the fan mode based on the last heat/cool mode that was used. I think it's a problem in their Android app too - I can only select which fan on the wall panel, but not in their app.

Ah, that's very interesting! I would have never guessed that's an option.
Using the cli above to grab json snapshots for "fresh air fan" and "recirculate fan" would be quite useful, perhaps if you could start a new issue here and post the json there that might be enough info to fix it.

If your unit does allow "heat with set fan speed" (like evap cool at set fan speed) it'd be helpful to know if that works with the current version?

**Comment by Rumbaar** [comment]
I've looked in HACS, and unless I'm missing something, I can't seem to find any version of this for installation.  How do I get it installed via HACS?  Or that not possible in current state?

**Comment by andrewleech** [comment]
@Rumbaar yes it works with hacs as a custom repository: https://hacs.xyz/docs/faq/custom_repositories/

**Comment by magedhv** [comment]
Hi guys, anyone got issues with Magiqtouch? It doesn't work anymore.
upon checking, I found it saying can't connect to the host!!

**Comment by andrewleech** [comment]
Closing this historical thread. Installation is now via HACS and the integration is on v5.2. If anyone has setup issues please open a new issue.
